name: Check

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: "check-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: {}
    env:
      NEXT_PUBLIC_SUPABASE_URL: "https://psbmuerdpmkajkkldqtz.supabase.co"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzYm11ZXJkcG1rYWpra2xkcXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNDE1NjcsImV4cCI6MjA3ODkxNzU2N30.JKaPS9tajIe6YJklEAdlih8a5xA-XgD3hStwKOEiihI"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
      - name: Type check
        run: bunx tsc --noEmit
      - name: Build
        run: bun run build
